# Generated by Django 4.0.1 on 2022-01-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoring',
            name='employerId',
            field=models.IntegerField(),
        ),
    ]
