# Generated by Django 4.0.1 on 2022-01-31 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0003_employee_delete_scoring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employeedId',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employerId',
            field=models.IntegerField(),
        ),
    ]
