# Generated by Django 4.0.1 on 2022-01-31 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0004_alter_employee_employeedid_alter_employee_employerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='includeAt',
            field=models.CharField(max_length=50),
        ),
    ]
