# Generated by Django 4.0.1 on 2022-02-02 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0005_alter_employee_includeat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employeedId',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employerId',
            field=models.IntegerField(unique=True),
        ),
    ]
